name: My first workflow
on: push
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List and read files
        run: | 
             echo "Hello, world!"
             ls -ltra
             cat README.md

      - name: Generate ASCII Artwork
        run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt