name: Generate ASCII Artwork

on: [push, fork]

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:  
        - name: Checkout Repo   
          uses: actions/checkout@v4

        - name: Execute Schell Script
          run: ./ascii-script.sh