name: Workflow Filters
on:
  repository_dispatch:
    types: [deploy-app]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Show deployment information
        run: |
          echo "Image: ${{ github.event.client_payload.image }}"
          echo "Tag: ${{ github.event.client_payload.tag }}"
          echo "Source repo: ${{ github.event.client_payload.source_repo }}"