name: Variable and Secrets Workflow
on: push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: siddharth1
    IMAGE_NAME: github-actions-nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        
        steps:
            - name: Docker Build
              run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

            - name: Docker Login
              env:
                DOCKER_PASSWORD: 242345346
              run: echo $DOCKER_PASSWORD | docker login $CONTAINER_REGISTRY -u $DOCKER_USERNAME --password-stdin

            - name: Docker Publish
              run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    deploy:
        runs-on: ubuntu-latest
        needs: docker
        env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: siddharth1
            IMAGE_NAME: github-actions-nginx
        steps:
            - name: Docker Run
              run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest